name: Test
on: [pull_request]
jobs:
  build:
    name: Windows Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      shell: bash
      if: always()
      run: |
        go test -v ./...
